### PR TITLE
Feature/add elections

### PR DESCRIPTION
**Pull request by Webnai**
Screenshot 2024-08-28 072213
completed add election screen

### CODE REVIEW

**Comment by Webnai** [comment]
@mikehammond I'm done with this issue

**Comment by mikehammond** [comment]
@Webnai Will take a look at this soon

**Comment by mikehammond** [comment]
@Webnai Are we not able to achieve the date pickers without bringing in the Material UI package?
Cos I am not very much for bringing in additional UI libraries aside Tailwind CSS.

**Comment by Webnai** [comment]
yes this has been a headache and the reason for the delayed push, with the regular date pickers  I was not able to implement the design and the default state of " start date" and "end date" for the dates, most of them had a default of dd/mm/yy, if I want to use the regular ones I would have to do the start and end date as a label at the top instead which won't be consistent with the design, really had a hard time on this

**Comment by mikehammond** [comment]
@Webnai Let's approach it like this then.
We get rid of the MUI and use the regular date pickers with Tailwind CSS so that I can merge this PR.
Then we get someone else on the team to specifically look at the 2 date pickers.
How does that sound?

**Comment by Webnai** [comment]
@mikehammond sounds good

**Comment by Webnai** [comment]
@mikehammond just made the push please review it

**Pull request merged**
