### PR TITLE
Develop the header component (#15)

### PR DESCRIPTION
**Pull request by kerimcanbalkan**
Implemented the Header component based on the Figma design.
Added navigation links and a "Connect Wallet" button.
Used existing images from the frontend/public/images folder.
Tested the component on the landing page.

This PR addresses issue #15.

Screen Shot 2024-08-18 at 17 39 48

### CODE REVIEW

**Comment by mikehammond** [comment]
@kerimcanbalkan Can I proceed to assign the issue #15 to you whiles I review this PR?

**Comment by kerimcanbalkan** [comment]
yes of course!

18 Ağu 2024 Paz 18:04 tarihinde Michael Hammond ***@***.***>
şunu yazdı:

**Comment by mikehammond** [comment]
@kerimcanbalkan Please leave a comment to signify taking up the issue #15 cos it seems that needs to happen before I can assign it to you.

**Comment by mikehammond** [comment]
@kerimcanbalkan Can we make use of the **Image** component available in Next.js cos it optimizes the image loading?
https://nextjs.org/docs/app/api-reference/components/image

**Comment by kerimcanbalkan** [comment]
I've added the changes

**Comment by mikehammond** [comment]
> I've added the changes

Excellent. Proceeding to merge this PR.

**Pull request merged**
