### PR TITLE
Feature/landing page

### LINKED ISSUE #17: Develop the Landing Page
Please refer to our Figma **Hi-Fi** page for the landing page excluding the **header** and **footer**.

https://www.figma.com/design/aJGE4crhpDJQnfH7ppH5vV/ABVS-UI?node-id=180-40&t=WMH9AMr2CFxGZmz1-4

- Work in the file **frontend/src/app/page.tsx** only.
- Locate your images to use in the **frontend/public/images**. Please do not rename any image.
- Visit the Landing at http://localhost:3000 to see your changes.
- Raise a PR when done.

Dependencies
- #13

### PR DESCRIPTION
**Pull request by Webnai**
Developed the landingPage
Added tailwind breakpoints to make responsive across all devices
Custom Css added in global.css
Screenshot 2024-08-21 170325
resolves #17

### CODE REVIEW

**Comment by mikehammond** [comment]
@Webnai Is there anyway to show evidence by using a service like [Loom](https://www.loom.com/) to record and share a link to the video recording?

**Comment by Webnai** [comment]
https://www.loom.com/share/3cac595dcef14769846042ed32171566?sid=e2a53e33-4a86-468c-a9e7-1cbc1047ac7a

yes here is a link to the recording

**Comment by Webnai** [comment]
when you run the application after some time the terminal throws an error
Invalid DOM property `enable-background`. Did you mean `enableBackground`?

this is found in header.tsx please also speak to the developer responsible for the header to fix that warning

**Comment by mikehammond** [comment]
> when you run the application after some time the terminal throws an error Invalid DOM property `enable-background`. Did you mean `enableBackground`?
> 
> this is found in header.tsx please also speak to the developer responsible for the header to fix that warning

@Webnai The developer for the Header.tsx file is an external person not on our team. It was hard for me to check their code so please fix any errors or warnings in there for me. I will really appreciate that. This time I have given you the go ahead to do that.

**Comment by mikehammond** [comment]
@Webnai There is also a preference of the Next.js Image component over HTML img tag.
Can we make use of the Image component available in Next.js cos it optimizes the image loading?
https://nextjs.org/docs/app/api-reference/components/image

**Comment by Webnai** [comment]
duly noted @mikehammond

**Comment by mikehammond** [comment]
@Webnai Are we good to go? Let me know when we are good to go so that I can merge this PR.

**Comment by mikehammond** [comment]
```
=============

./src/app/page.tsx
81:39  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
```
@Webnai I am getting the LINTING error above in the landing page. Please attend to it.
You also run `npm run lint` on your end to get the results.

**Comment by Webnai** [comment]
with this last commit we should be good to merge the PR

**Pull request merged**
