### PR TITLE
developed check voter eligibility page

### LINKED ISSUE #36: Develop the Check Voter Eligibility Page
Please refer to our Figma **Hi-Fi** page https://www.figma.com/design/aJGE4crhpDJQnfH7ppH5vV/ABVS-UI?node-id=536-105&t=37C8a1yiJoCRKdGO-4

- Work in the file **frontend/src/app/elections/[id]/verify/page.tsx** only.
- Locate your images to use in the **frontend/public/images**. Please do not rename any image.
- Visit the Landing at http://localhost:3000/elections/1/verify to see your changes.
- Raise a PR when done.

### PR DESCRIPTION
**Pull request by AngeloKwakye**
resolves #36

### CODE REVIEW

**Comment by mikehammond** [comment]
@AngeloKwakye I have broken down some part of the code into a component.
Take a look and do the work you wanted to do in the `VerifyVoter.tsx` component.

**Comment by AngeloKwakye** [comment]
awesome 👍🏾

**Comment by AngeloKwakye** [comment]
@mikehammond i think my work here is done.
all yours now.

**Comment by mikehammond** [comment]
@AngeloKwakye Thank you very much.
Will review and merge it.

**Comment by AngeloKwakye** [comment]
awesome 👍🏾

**Review by mikehammond — APPROVED** [review]

**Pull request merged**
